appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: HXpGnw5FCNcFWMv2ja0m2KrGdPoHECfloFHPlMAqhmFSlA/8WHjIMLAPJwoy1pIXg2HcSVKalM5uzazA8f8Mf7tpylCsxV+oQsEzHNfTLqo/8ftxJn7Ira2hjsEcL1P2yT7ZDf8MzHoG8m6LAdE+yiA52U3ezoNfV4sSl0Hy3ormFJhHgzh4UJtEWKchVomGy6/igXvNAX3ojUzIpfW0xOcnpC0VanDG3YfPFaOgxCUl8c4nHx6SK36bTjrp/Zrchhku1JQ7oD1OT7/vxSAvINnW+FqK+nDTI+tEQ/+Uo9Ma0qh6hgBQN2Q3VE2loyqR/hAQW5w/wox6sM4brbpVxL64o9549X6zDwkiejS8x3f7OBn81qQijLDc+tqYssygDGuR0QztLXrcFFr7xlCMIMxi3w2X3iENVYMew3cicjfg+SgUpeUgVS73tOfUGcm9EeRYRE6Mp6d6iQYmKztfbFNvwqV64xpx3Wdp9QYI8NEJxlElA6Q0Tm0kCIK9ax7da5Jj06J9qSup3h20I47fWUa2FOOIilrwKSlaNYpfu/v4TumhEAT0/IsvvVv3/TGkGAiY9rx0huddoRtvS4TNlHPCBDAl24dpivKTrVBFuBjoCP9C2RqHSPG84SmfuOpoX4BWF9wPEJHUpmiu50MJD3jZ8RKUZrJsl+XwZ5nyPcE=}
